### DISCUSSION TITLE
How to prevent that Arco Design looses its style in favor the browser autofill behavior

### DISCUSSION THREAD

**Discussion by calebeaires** [arco-design/arco-design#487] [Q&A] [answered]
Arco Design input has a gray background by default. It is beautiful, but browsers input autofill fights with it making design not so cool

![CleanShot 2022-01-22 at 11 30 23](https://user-images.githubusercontent.com/794195/150642721-2e82b3be-dc35-4295-ab48-e2fb1230400b.png)

I have tried to fix it, but I had no success. Do you guys have some idea to fix that? Here is what I have tried to do:

```css
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus,
input:-webkit-autofill:active {
  transition: background-color 5000000s ease-in-out 0s;
  background: gray;
}

input:-webkit-autofill {
  background: gray;
}

```

**Comment by calebeaires** [comment, marked as answer]
After some digging I find out this solution. 


```css
input:-webkit-autofill,
input:-webkit-autofill:focus,
input:-webkit-autofill:active {
  transition: background-color 5000000s ease-in-out 0s;
  -webkit-box-shadow: 0 0 0 1000px var(--color-fill-2) inset !important;
}

input:-webkit-autofill:hover {
  transition: background-color 5000000s ease-in-out 0s;
  -webkit-box-shadow: 0 0 0 1000px var(--color-fill-3) inset !important;
}

input:-webkit-autofill:focus-within {
  transition: background-color 5000000s ease-in-out 0s;
  -webkit-box-shadow: 0 0 0 1000px var(--color-bg-2) inset !important;
}

```
![CleanShot 2022-01-22 at 11 52 09](https://user-images.githubusercontent.com/794195/150643488-70901035-c1a6-4266-9a0e-52461036e106.png)


But still, you guys could help improve it!
