### ISSUE TITLE
the dynamic style variable of Table scrollbar 

### ISSUE THREAD

**Issue by quanscheng** [arco-design/arco-design#1592]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## What are the similar cases of this feature
no

## What problem does this feature solve?
 The color of  the Table scrollbar changes when styles change

**Comment by quanscheng** [comment]
Then I added those styles to the global index.less
```less
.arco-table-layout-fixed .arco-table-content-inner {

  &::-webkit-scrollbar {
    background-color: var(--color-bg-4);
    height: var(--border-radius-medium);
  }

  &::-webkit-scrollbar-track-piece {
    background-color: var(--color-neutral-2);
  }

  &::-webkit-scrollbar-thumb {
    background-color: var(--color-text-4);
    border-radius: var(--border-radius-large);
  }

  &::-webkit-scrollbar-thumb:hover {
    background-color: var(--color-text-3);
  }
}
```
![image](https://user-images.githubusercontent.com/68772719/203308518-16bfc75c-720c-4684-b351-2b7b4b361740.png)
![image](https://user-images.githubusercontent.com/68772719/203308689-8b4b4b00-944c-4b80-9bad-086bed4b13f2.png)
