### ISSUE TITLE
pr-check ci problem of permissions github secret

### ISSUE THREAD

**Issue by ChelesteWang** [arco-design/arco-design#25]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info
- **依赖包名 及 版本:** 无依赖
- **系统版本:** 2.23.3
- **浏览器版本:** 无关
- **复现地址:** https://github.com/arco-design/arco-design/runs/4011273482?check_suite_focus=true

## 预期结果
```yml
 - name: report coverage
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: echo "done"
```

## 复现步骤
创建 pr 时由于创建 pr 的人权限不足导致 secret 出现问题
Error: Resource not accessible by integration
