### ISSUE TITLE
【急/求救】arco.css 和 arco.min.css 中有致命语法错误

### ISSUE THREAD

**Issue by fz6m** [arco-design/arco-design#570]
`arco.css` 和 `arco.min.css` 里有这个：

```css
.arco-input-tag:not(.arco-input-tag-focus)-clear-icon:hover::before {
  background-color: var(--color-fill-4);
}
```

压缩器识别到了 `-clear-icon` 语法错误 😭😭😭😭😭😭😭😭😭😭

求救
