### ISSUE TITLE
Descriptions 的 horizontal 布局在设置了 scroll.x 的 Table 展开行中 label 宽度异常

### ISSUE THREAD

**Issue by wildseeder** [arco-design/arco-design#707]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.31.1
- **Browser:** chrome100.0.4896.60
- **Reproduction Link:** https://codepen.io/wildseeder/pen/rNpzPdx

## What is expected?
Descriptions 的 label 宽度正常显示

## Steps to reproduce
1. Table 设置 scroll.x
2. Descriptions 设置 layout='horizontal'

**Comment by Megrax** [comment]
看了下，这个问题产生的原因在于：给 Table 设置 scroll.x 时，会给该 Table 增加 `table-layout: fixed;` 的样式。而内部的 Descriptions 组件也是用 table 实现的，因此内部的 Descriptions 组件的 table 元素也顺带获得了 `table-layout: fixed;`，从而导致 label 一列的宽度不再由内容的宽度决定。
```html
...
<div class="... arco-table-layout-fixed ...">
  ...
  <table> <!-- 外层的 Table -->
    ...
    <table> <!-- 内层的 Descriptions -->
```
```css
.arco-table-layout-fixed {
  table {  /* 同时影响了内外两层的 table，但是我们只希望对最外层应用 */
    table-layout: fixed;
  }
}
```
解决方式最好是让外层 Table 的 `table-layout` 样式只影响到这一层的 table，而不影响到内部嵌套的其他 table。我试着修了一下 #730 ，但是不知道是不是最好的方式：
```css
.arco-table-layout-fixed {
  table { 
    table-layout: fixed;
  }
  table table { 
    table-layout: auto;
  }
}
```
cc @PengJiyuan @MisterLuffy

**Comment by wildseeder** [comment]
@Megrax 这可能会覆盖内层 table 的 table-layout 值而引起用户样式异常，建议指定外层 table 的类名或使用类似选择方式：

```css
.arco-table-layout-fixed .arco-table-content-inner > table {
  table-layout: fixed;
}
```

**Comment by Megrax** [comment]
测了一下确实有这个问题，修改为了
```css
.arco-table-layout-fixed {
  .arco-table-content-inner > table {
    table-layout: fixed;
  }
}
```
这样应该可以使 Table 上设置的 `table-layout: fixed;` 样式只限制于 Table 本身，而不会影响到内部嵌套的其它基于 table 实现的组件样式。
