### ISSUE TITLE
DOC: Icon's name element overflows

### ISSUE THREAD

**Issue by anderlaw** [arco-design/arco-design#82]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info
- **依赖包名 及 版本:** -
- **系统版本:** -
- **浏览器版本:** -
- **复现地址:** https://arco.design/react/components/icon

## 预期结果
the element should be inside its parent element
It should be:
<img width="527" alt="截屏2021-10-31 下午6 15 30" src="https://user-images.githubusercontent.com/21139011/139577898-9c4a217d-1a73-4ed0-bc7d-c61bf2c24b4a.png">

while currently:
<img width="499" alt="截屏2021-10-31 下午6 16 48" src="https://user-images.githubusercontent.com/21139011/139577967-65bb29f7-4e1e-444b-885e-3b7038c11c8c.png">

## 复现步骤
1. open that URL,
2. scroll to the Icon section
3. mouse hover on the name element
4. you will find out that 

## maybe useful code
```css
.ac-content ul.iconlist .icon-cell .name {
    /*...*/
    text-align: center;
    box-sizing: border-box;
    padding: 12px;
    margin: 0;
}
```
